### ISSUE TITLE
Optimal problem declared dual infeasible

### ISSUE THREAD

**Issue by mlubin** [MPF-Optimization-Laboratory/ConicIP.jl#9]
Here's another one: https://gist.github.com/mlubin/6bc8d916d44e9766056bb582dea4b5da

ECOS reports:

```
ECOS 2.0.5 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +1.501e+04  -1.667e+04  +3e+05  2e-04  3e-05  1e+00  1e+04    ---    ---    1  1  - |  -  - 
 1  +1.449e+04  -1.601e+04  +3e+05  2e-04  3e-05  2e+01  1e+04  0.0377  4e-02   2  2  2 |  0  0
 2  +1.365e+04  -1.498e+04  +3e+05  2e-04  2e-05  6e+01  1e+04  0.0623  4e-02   2  2  2 |  0  0
 3  +1.034e+04  -1.102e+04  +2e+05  2e-04  2e-05  2e+02  1e+04  0.2574  4e-02   1  1  1 |  0  0
 4  +6.453e+03  -6.772e+03  +1e+05  1e-04  1e-05  3e+02  6e+03  0.3847  4e-02   1  1  1 |  0  0
 5  +1.019e+03  -1.010e+03  +2e+04  2e-05  2e-06  2e+02  1e+03  0.8567  3e-02   1  1  1 |  0  0
 6  +3.517e+02  +1.078e+02  +3e+03  2e-06  2e-07  3e+01  1e+02  0.8805  7e-03   1  1  1 |  0  0
 7  +9.057e+02  +7.586e+02  +2e+03  1e-06  1e-07  3e+01  9e+01  0.5070  3e-01   2  2  2 |  0  0
 8  +1.335e+03  +1.313e+03  +3e+02  2e-07  2e-08  7e+00  1e+01  0.8587  2e-02   2  2  2 |  0  0
 9  +1.460e+03  +1.457e+03  +5e+01  3e-08  4e-09  2e+00  2e+00  0.9078  8e-02   2  1  1 |  0  0
10  +1.481e+03  +1.481e+03  +2e+00  1e-09  1e-10  5e-02  7e-02  0.9701  1e-04   1  1  1 |  0  0
11  +1.481e+03  +1.481e+03  +7e-02  5e-11  8e-12  2e-03  3e-03  0.9563  6e-04   1  1  1 |  0  0
12  +1.481e+03  +1.481e+03  +2e-03  1e-12  8e-13  5e-05  7e-05  0.9778  1e-03   2  1  1 |  0  0
13  +1.481e+03  +1.481e+03  +4e-05  7e-14  8e-14  1e-06  2e-06  0.9717  3e-04   2  1  1 |  0  0
14  +1.481e+03  +1.481e+03  +9e-07  1e-15  9e-15  3e-08  4e-08  0.9797  1e-04   1  1  1 |  0  0

OPTIMAL (within feastol=9.1e-15, reltol=6.2e-10, abstol=9.1e-07).
Runtime: 0.000719 seconds.
```

ConicIP reports:

```
 > INTERIOR POINT PREPROCESSOR v0.7 (July 2016)

   - No changes made

 > INTERIOR POINT SOLVER v0.7 (July 2016)

   Iter  Mu          prFeas      duFeas      muFeas      refine    
      1  2.4280e+08  9.0234e-01  8.9197e+00  1.1568e+00  0

 > EXIT -- Dual Infeasible!
```

CC @chriscoey

**Comment by gabgoh** [comment]
This was a tricky one to debug :p 

The problem here seems to be that there are two different ways of calculating the infeasibility residual, one favored by cvxopt and the other by ecos (see https://github.com/embotech/ecos/blob/faef9461f228afcc8b44103d7419ac2fec88a368/src/ecos.c#L533). 

Specifically, cvx prefers certificates of this kind

```
Ay ≧ 0,  Gy = 0,  Qy = 0,  cᵀy = 1 
```

while ECOS prefers certificates of this kind

```
Ay ≧ 0,  Gy = 0,  Qy = 0,  cᵀy > 0,  norm(y) = 1
```

The difference is that the ECOS certificates do not have a dependence on the norm of c. (and it's hard to normalize the norm of c out of the measure for various reasons). The norm of c here is about 60000, so those are the few extra digits that push the CVXOPT into a false positive. I should have a push coming with the changes.

At any rate, I'm not sure what the tradeoff really is, I've added both options as an option to be passed in, with the solver defaulting to the ECOS solution.

these bug reports seem to reveal some pretty deep and interesting bugs, keep them coming :+1:

**Comment by gabgoh** [comment]
ok i've fixed this bug, and integrated it into the tests

**Comment by mlubin** [comment]
Mmm, now the problem is declared infeasible. The unit tests are failing: https://travis-ci.org/MPF-Optimization-Laboratory/ConicIP.jl/jobs/153156824#L905

**Comment by gabgoh** [comment]
oh oops, it was just a typo. wrote 1e-10 as 1e-100. It's fixed now.

**Comment by mlubin** [comment]
Well good job, I'm fresh out of problems where ConicIP doesn't converge, I'd say it's now more reliable than ECOS on my SOCP test set. CC @SteveDiamond

There seem to be some cases where ConicIP is much slower than ECOS, but I'll open separate issues for that.

**Comment by mlubin** [comment]
(@SteveDiamond, you can call ConicIP through the same cmpb interface as before.)
